### ISSUE TITLE
The Sep 6 commit has overwritten some earlier changes

### ISSUE THREAD

**Issue by nkotilainen** [OpenNuvoton/N76E003-BSP#1]
See for example line 126 of Sample_Code/I2C_Master-Slave/I2C_Slave/Code/I2C_S.c, it was fixed in July 2017 but has reverted now to the old version.

**Comment by Jen-Chih-Liu** [comment]
set_P0SR_6;                             //set SCL (P06) is  Schmitt triggered input select.
The sample code, add i2c Schmitt triggered input select enable for reference.

**Comment by nkotilainen** [comment]
Hi! Note that P06 is the wrong pin, it's not SCL. This was fixed earlier, but then the fix was overwritten by a later commit.
